In [2]:
import numpy as np
import pandas as pd

#### Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix

In [8]:
array = np.arange(1,11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
array = np.arange(1,11).reshape(2,5)
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

#### Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index

In [30]:
array_1 = np.arange(1,21)
array_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [34]:
extracted_elements = array_1[5:16]
extracted_elements

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

#### Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a new item to the series with the key 'pears' and the value 4.

In [37]:
series = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})
series

apples     3
bananas    2
oranges    1
dtype: int64

In [41]:
series['pears'] = 4
series

apples     3
bananas    2
oranges    1
pears      4
dtype: int64

#### Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data

In [44]:
names = ["Aleena", "Bhaskar", "Manu", "Dohni", "Smrithi", "Enzo", "Anu", "Gayathri", "Dileep", "Rohit"]
ages = [25, 32, 24, 43, 22, 35, 28, 27, 45, 30]
genders = ["F", "M", "M", "M", "F", "M", "F", "F", "M", "M"]
df = pd.DataFrame({'name': names, 'age': ages, 'gender': genders})

In [46]:
df

name  age gender
0    Aleena   25      F
1   Bhaskar   32      M
2      Manu   24      M
3     Dohni   43      M
4   Smrithi   22      F
5      Enzo   35      M
6       Anu   28      F
7  Gayathri   27      F
8    Dileep   45      M
9     Rohit   30      M

#### Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe.

In [49]:
occupations = ["Programmer", "Manager", "Analyst", "Programmer", "Manager", "Analyst", "Programmer", "Manager", "Analyst", "Programmer"]
df['occupation'] = occupations

In [51]:
df

name  age gender  occupation
0    Aleena   25      F  Programmer
1   Bhaskar   32      M     Manager
2      Manu   24      M     Analyst
3     Dohni   43      M  Programmer
4   Smrithi   22      F     Manager
5      Enzo   35      M     Analyst
6       Anu   28      F  Programmer
7  Gayathri   27      F     Manager
8    Dileep   45      M     Analyst
9     Rohit   30      M  Programmer

#### Select the rows of the dataframe where the age is greater than or equal to 30.

In [54]:
age_greater_or_equal_to_30 = df[df['age'] >= 30]

In [58]:
age_greater_or_equal_to_30

name  age gender  occupation
1  Bhaskar   32      M     Manager
3    Dohni   43      M  Programmer
5     Enzo   35      M     Analyst
8   Dileep   45      M     Analyst
9    Rohit   30      M  Programmer

#### Convert this dataframe to a csv file and read that csv file, finally display the contents.

In [62]:
df.to_csv("data.csv", index=False)

In [68]:
df_read = pd.read_csv("data.csv")
print("Exercise 7:\n", df_read)

Exercise 7:
        name  age gender  occupation
0    Aleena   25      F  Programmer
1   Bhaskar   32      M     Manager
2      Manu   24      M     Analyst
3     Dohni   43      M  Programmer
4   Smrithi   22      F     Manager
5      Enzo   35      M     Analyst
6       Anu   28      F  Programmer
7  Gayathri   27      F     Manager
8    Dileep   45      M     Analyst
9     Rohit   30      M  Programmer
